-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mar. 08 juin 2021 à 09:21
-- Version du serveur :  10.4.17-MariaDB
-- Version de PHP : 8.0.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `salon_pst_pfh`
--

-- --------------------------------------------------------

--
-- Structure de la table `pst2a`
--

CREATE TABLE `pst2a` (
  `id_EquipePST` int(11) NOT NULL,
  `num_EquipePST` text NOT NULL,
  `nom_PST` text NOT NULL,
  `descriptif_PST` text NOT NULL,
  `equipe_PST` text NOT NULL,
  `image_PST` text NOT NULL,
  `tutor_PST` text NOT NULL,
  `phrase_acroche` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Structure de la table `pst3a`
--

CREATE TABLE `pst3a` (
  `id_EquipePST` int(11) NOT NULL,
  `salle` text NOT NULL,
  `horraire` text NOT NULL,
  `num_EquipePST` text NOT NULL,
  `nom_PST` text NOT NULL,
  `descriptif_PST` text NOT NULL,
  `equipe_PST` text NOT NULL,
  `image_PST` text NOT NULL,
  `tutor_PST` text NOT NULL,
  `phrase_acroche` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Structure de la table `pfh`
--

DROP TABLE IF EXISTS `pfh`;
CREATE TABLE IF NOT EXISTS `pfh` (
  `id_EquipePFH` int(11) NOT NULL,
  `nom_PFH` varchar(100) NOT NULL,
  `phrase_acroche` varchar(200) NOT NULL,
  `descriptif_PFH` text DEFAULT NULL,
  `imagePFH` varchar(100) DEFAULT NULL,
  `stand` int(11) DEFAULT NULL,
  `salle` varchar(30) DEFAULT NULL,
  `tutor_PST` varchar(30) NOT NULL,
  PRIMARY KEY (`id_EquipePFH`),
  UNIQUE KEY `nom_PFH` (`nom_PFH`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


--
-- Déchargement des données de la table `pst3a`
--

INSERT INTO `pst3a` (`id_EquipePST`, `salle`, `horraire`, `num_EquipePST`, `nom_PST`, `descriptif_PST`, `equipe_PST`, `image_PST`, `tutor_PST`, `phrase_acroche`) VALUES
(1, 'I11', 'AM', 'Equipe 30A ', 'B.I.L.A.L – Boîtier Intelligent Libre pour Automobile Légère', 'Connecté au port OBD, le boîtier B.I.L.A.L accède directement aux données de votre véhicule et traduit les informations afin de suivre sa consommation et sa position en temps réel et en permanence.\r\nGrâce à notre application, vous pouvez consulter vos statistiques trajet ainsi que la position de votre voiture n’importe où et n’importe quand.\r\n', 'TOY-RIONT LE DOSSEUR Elouan (Chef de projet), ARNOUX Julie, \r\nDELIERE Charles,\r\nDELAYE Eliott,\r\nBRILLET Pierre-Louis', 'images_pst3A/B.I.L.A.L.jpg', 'Mme ALKASM Sulaf', 'Un boîtier connecté pour une consommation + responsable'),
(2, 'I02bis', 'PM', 'Equipe 30B', 'The Quest of Tataë\r\n', 'The Quest of TATAË est un RPG pour 3 à 4 joueurs, conçu pour donner le meilleur de ce genre couplé au plaisir du multijoueur. Explorez de sombres cryptes, partez à la recherche d’anciens artefacts et rencontrez de nouveaux alliés dans ce jeu innovant et fun !', 'ARCHAMBEAU Thomas (Chef de Projet),\r\nVAISSAIRE Eléonore,\r\nCHANSOU Tristan,\r\nDESCHAMPS Aymeric,\r\nCLÉMENT Aimeric,\r\n', 'images_pst3A/The Quest of Tataë.jpg\r\n', 'Félicia IONASCU', 'Un RPG multijoueur, c’est pas banal !'),
(3, 'I02', 'AM', 'Equipe 30C', 'Borne COVID', 'PAS ENVOYER', 'HAASTRUP THEO (Chef de Projet),\r\nFRATACCI Emeline,\r\nBERNARD Hippolyte,\r\nETHEVE Gabriel,\r\nMOUTASSAMY Jahmali\r\n', 'PAS ENVOYER', 'Chiraz TRABELSI', 'PAS ENVOYER'),
(4, 'I02bis', 'PM', 'Equipe 30D', 'ERGO DOMO', 'Les « smart house » sont des maisons entièrement connectées permettant notamment au propriétaire de garder le contrôle sur son domicile peu importe sa localisation.  Le PST « Ergo Domo » vise à reproduire une maquette d’une maison contenant les fonctionnalités que l’on pourrait retrouver au sein d’une smart house. Ainsi, c’est à travers l\'application Blynk » que l’utilisateur peut la contrôler.', 'CHU YEW YEE Andréa\r\nALVES Quentin\r\nTENAILLEAU Sarah-Angélique\r\nFENG Xinyao\r\nBENMEHIDI Takia\r\n', 'images_pst3A\\ERGO DOMO.png', 'Nadine KHODOR', 'Parce que VOUS méritez une BONNE maison.'),
(5, 'I11', 'AM', 'Equipe 30E', 'F.D.B.', 'Notre projet s\'intitule FDB, ce nom a été donné en raison des différentes significations qu\'il avait pour nous, telles que «Fais Des Billets» (Gagner de l\'argent) ou «Fais Du Bitcoin».\r\nEn effet, l’objectif fondamental de notre projet est de créer un logiciel permettant à un utilisateur de tester la stratégie de trading, avec l\'utilisation d\'API et de courtiers. Nous voulons que ce logiciel soit facile d\'accès, et majoritairement ajustable en fonction des techniques ou des sentiments de l’utilisateur en matière de marchés financiers. Ce projet fusionne à la fois notre passion, notre intérêt et nos études, et présente une belle opportunité de valoriser de manière parallèle nos compétences en ingénierie et nos connaissances financières.\r\n', 'OZOUF Jonathan,\r\nAMALAN KANNAN Baptiste,\r\nRENAUD--PARREIRA Anthony,\r\nMEYER Alexandre,\r\nSCEMAMA Johanne,\r\nGENOVESE Mélissa\r\n', 'images_pst3A\\F.D.B.jpg', 'Nadine KHODOR', 'La Meilleure Stratégie de Trading est l’Automatisation.'),
(6, '', '', 'Equipe 31A', 'Vidéo surveillance & streaming\r\n', 'En quelques clics, bénéficiez d’une surveillance de votre domicile.\r\n\r\nIl vous suffira d’installer nos caméras, serveur et application afin de surveiller votre domicile.\r\n\r\nNotre algorithme permet de détecter les intrus qui pénètrent chez vous. Il utilise la détection humaine. \r\n\r\nUne alerte vous sera envoyée pour vous permettre de visionner les caméras en temps réel et de conserver l’enregistrement vidéo.\r\n', 'NOUAR Manelle,\r\nPROUX Angélique, \r\nLEJEUNE Gael, \r\nCHAUVREAU-MANAT Steve, \r\nOBADI Anas, \r\nBELRHITI ALAOUI Habiba\r\n', 'images_pst3A/VIDÉO SURVEILLANCE & STREAMING.jpg\r\n', 'Vlad VALICA', 'Travaillons ensemble pour votre sécurité au quotidien !'),
(7, '', '', 'Equipe 31B', 'Monture équatoriale de téléscope\r\n', 'Notre projet vise la fabrication d’une monture équatoriale de télescope dite « GoTo », complètement autonome : une monture automatisée dans le pointage de l’astre que l’on souhaite observer, disponible dans une base de données logicielle sur un ordinateur. Cette monture est transportable partout : il lui suffit d’un support et d’un ordinateur. Choisissez votre étoile, et observez !', 'BUI Sylvain,\r\nCOLLATY Srikanth,\r\nMADAD Sarra,\r\nLOUATY Nour-El-Houda,\r\nLECLERC Maxence\r\n', 'images_pst3A/Monture équatoriale de téléscope.jpg\r\n', 'Sylvie ZAGO \r\n', '« Le ciel n’a jamais été aussi près. »');

--
-- Déchargement des données de la table `pfh`
--

INSERT INTO `pfh` (`id_EquipePFH`, `nom_PFH`, `phrase_acroche`, `descriptif_PFH`, `imagePFH`, `stand`, `salle`, `tutor_PST`) VALUES
(1, 'Projet Ballon Sonde', '“Le climat change, pourquoi pas vous ?”', 'PFH Ballon sonde, mais qu’est-ce que c’est que ce truc encore ? \r\nEh bien, c’est un projet collaboratif porté par Air ESIEA qui a pour but de sensibiliser le grand publique aux enjeux du développement durable en permettant une collecte de données utiles aux chercheurs et agriculteurs tout en impliquant des étudiants d’école d’ingénieur. Tout le monde peut mettre la main à la pâte alors... Qu’est-ce que vous attendez pour sauter le pas ?\r\n', 'images_pfh\\ESIEA.png', 28, 'I12-a', 'Ball sonde'),
(2, 'Conférence Sci’Tech', 'Plus de conférences pour plus de connaissances', 'Le projet Conférences Sci’Tech a pour but d’organiser des conférences autour de sujets scientifiques et techniques. L’objectif est de présenter une fois par mois un sujet techniques ou scientifiques. Cette année, nous avons décidé d’intégrer des conférences dédiées au développement durable tous les deux mois. ', 'images_pfh\\Sci.png', 25, 'I12a', 'Sci'),
(3, 'Projet New Horizons', 'Notre projet consiste à créer un programme de mentorat pour les premières et deuxièmes années.', 'Notre projet consiste à créer un programme de mentorat pour les premières et deuxièmes années, fabrication de fusées à eau et une conférence sur les satellites.', 'images_pfh\\ESIEA.png', 39, 'I14', 'newhoriz'),
(4, 'Projet Kaléidoscopes', 'Le projet consiste à confectionner des bières imaginées par les étudiants.', 'Le projet consiste à confectionner des bières imaginées par les étudiants pour en apprendre le processus de création et faire partager ces connaissances à tout le monde. Le but étant de passer le meilleur des moments entre étudiants autour d\'une dégustation !', 'images_pfh\\KALEIDOSCOPES_AFFICHE_PFH_SALON.png', 40, 'I14', 'kaleidos'),
(5, 'Projet Tracking Game', 'Venez découvrir Montmartre et ses mystères !', 'Le Tracking Game est une course d’orientation. Elle sera organisée le 07 Juin à Montmartre avec le soutien de l’association internationale ! Le but est de faire visiter les plus petits recoins de Paris tout en se divertissant. Tous les étudiants et le personnel de l’ESIEA sont invités. \r\nNous vous y attendons nombreux !\r\n', 'images_pfh\\Affiche_PST_Tracking_game.JPG', 40, 'I14', 'trackjam'),
(6, 'Projet Food Discovery', 'Venez voyager en mangeant !', 'Le PFH “Food Discovery” est un PFH de l’association internationale de l’ESIEA. Il a pour but de faire découvrir aux étudiants des plats provenant de cultures étrangères. Pour ce faire, nous partageons des recettes sur différentes plateformes. Vous pourrez en effet nous retrouver, trois fois par semaine sur notre page Instagram ou une fois par mois sur notre chaîne YouTube où nous vous partageons des idées de nouvelles recettes.', 'images_pfh\\PFH Food Discovery.JPG', 42, 'I14', 'food_discovery'),
(7, 'organisation du Hackathon', '', NULL, 'images_pfh\\ESIEA.png', 24, 'I11', 'hackaton'),
(8, 'Projet Découverte de l’informatique auprès des collégiens et lycéens', 'Découverte de l\'informatique auprès des collégiens et des lycéens.', 'Les objectifs de ce projet sont liés à la réalisation de différents rendez-vous avec les étudiants, que ce soient des collégiens et/ou des lycéens. Pour le moment, nous prévoyons deux rencontres lors des journées portes-ouvertes. Le meilleur cas possible serait de les faire en présentiel mais au vu des conditions sanitaires nous envisageons de les faire en ligne. Lors de ces différentes rencontres d’autres objectifs sont induits. Tout d’abord de transmettre aux étudiants notre intérêt aux différentes thématiques de l’informatique grâce aux ateliers que nous mettrons en place. Enfin la sensibilisation au développement durable, fil rouge du programme PFH de cette année.', 'images_pfh\\DI.png', 103, 'E06', 'Decouvert_IT'),
(9, 'Projet Securitech', 'Just hack it', 'Securitech a été l’un des premiers concours de sécurité informatique organisé en France en 2002. Ce PFH inaugurera sa 5e édition et célébrera les 20 ans du challenge. Notre objectif principal est de toucher le plus grand nombre de personnes autour du domaine de la cybersécurité. \r\nLe projet se compose de niveaux pour les débutants mais également pour les plus chevronnés. \r\n', 'images_pfh\\Affiche_Securitech_720-420.png', 104, 'E06', 'SecTech'),
(10, 'E-LAN', 'Evénement autour des passionnés de jeux vidéo compétitif.', 'E-Lan est un évènement autour du jeux vidéo compétitif qui a pour but d\'organiser 3 manifestations durant l\'année scolaire. Le but est de réunir des passionnés et de leur faire passer un moment inoubliable. La nouveauté de cette édition 2020-2021, une e-Lan caritative, avec pour objectif de récolter des dons pour une association grâce aux inscriptions des tournois de jeux.', 'images_pfh\\logo E-lan 2020-2021 avec date.png', 23, 'I11', 'E-LAN'),
(11, 'Projet Pour un Sourire', 'Apporter de la joie, réchauffer des cœurs et créer des sourires.', 'Nous sommes le PFH « Pour un sourire ». Notre équipe est composée de 11 personnes et avons pour objectif d’aider les personnes dans le besoin. Nos missions : \r\n•	Organisation d’une maraude (Distribution alimentaire + kit de survie) à Paris à destination des personnes les plus démunies.\r\n•	Création d’une cagnotte afin de financer un puits pour l’accès à l’eau potable dans un pays dans le besoin.\r\n', 'images_pfh\\Logo pour un sourire.png', 58, 'Extension', 'proj sourire'),
(13, 'Projet Gala – Sponsoring et partenariat Voile', '', NULL, 'images_pfh\\Voile ESIEA image site.png', 36, 'I13', 'spon partenar'),
(14, 'Projet GameJam', 'ESIEA Jam organise un concours de création de jeux vidéo par équipe.', 'L\'ESIEA Jam organise un concours de création de jeux vidéo par équipe, aussi appelé une Game Jam. \r\nDe plus, pour que tout le monde soit au même niveau et puisse faire un jeu vidéo avec ses amis, nous organisons également des sessions d\'entraînement, qui se déroulent sous forme de cours dans lesquels vous pourrez apprendre l\'utilisation de différents logiciels techniques.', 'images_pfh\\affiche web format 720 240 (portrait).jpg', 21, 'I11', 'ESIEA Jam'),
(15, 'Projet Désintégration', 'La soirée de désintégration est la soirée qu’il ne faut pas rater si tu es étudiant à l’ESIEA ! ', 'La soirée de désintégration qu’est-ce que c’est ?\r\nC’est  l’une des plus grosses soirées de l\'école, elle regroupe toutes les générations pour célébrer les derniers instants des 5A avant leur départ en stage et la fin du semestre. Cette soirée commandée par le BDS créé un grand moment de cohésion.\r\n', 'images_pfh\\ESIEA.png', 31, 'I13', 'Desint'),
(16, 'Projet Sport et Nutrition', 'Un esprit sain dans un corps sain !', 'Ce projet est inventé par le bureau des sports, consiste à créer du contenu dynamique, sur les réseaux sociaux, soit par une photo ou vidéo d’une recette “healthy”, soit par des photos ou vidéos proposant un entrainement ou un exercice physique, sinon en partageant des bons plans et astuces tant sur la nutrition ou le sport. Tout cela pour créer une solidarité et une communauté pour reprendre ou continué un mode de vie sain.', 'images_pfh\\ESIEA.png', 32, 'I13', 'Sp-Nutrit'),
(17, 'Projet Troph’Esiea', 'Tournois sportif inter-campus Paris-Laval.', 'Cet événement sportif a pour but de renforcer les liens entre le campus de Paris et celui de Laval.\r\nL’objectif de notre projet est de créer une cohésion entre les différents acteurs de l’ESIEA et de partager de bonnes expériences tout en sensibilisant les participants au développement durable.\r\n', 'images_pfh\\Troph\'ESIEA.png', 33, 'I13', 'Troph\'esiea'),
(18, 'Projet Civilisation et Culture', 'Devenez le Qin de la culture !', 'Salut !\r\nTu veux devenir un “Qin de la culture ?” alors notre PFH Civilisation et culture et le BDA vous présentent le projet : A la découverte de la civilisation Qin ! Nous allons vous présenter différents aspects de la civilisation à travers son histoire, des jeux en ligne sur la culture chinoise et un tutoriel de cuisine pour reproduire une recette locale typique !\r\n', 'images_pfh\\PFH Civilisation & Culture.JPG', 43, 'I14', 'civ_culture'),
(19, 'Projet Théâtre', 'Venez fêter la réouverture des théâtres avec la troupe Ohana !', 'Envie de vous évader et de changer d’air ? Venez voir notre pièce de Théâtre !\r\nMêlant les thèmes de l’amitié, du rêve et de la musique, notre pièce raconte l’histoire d’amis qui se réunissent et organisent un spectacle afin de pouvoir collecter des fonds pour sauver un théâtre.\r\nInspiré du film d’animation TOUS EN SCÈNE réalisé par Hammer & Tongs en 2016, nous avons écrit à l’aide de nos doigts de fées notre pièce à ne pas rater !', 'images_pfh\\PFH_theatre_720x420.png', NULL, 'Extension B02 - estrade', 'Proj_theatre'),
(20, 'Projet Accompagnement de la transformation numérique de la Croix Rouge', 'Projet Accompagnement de la Transformation Numérique de la Croix-Rouge.', 'Au sein de la filière personnes âgées et domicile, la Croix-Rouge française à effectuer un déploiement numérique. Celui-ci comprend de nombreux équipement (Tablettes, Casques VR et Casques de Musicothérapie) et des logiciels. Notre projet vise à récupérer un retour de la part du personnel et des personnes âgées. Cela dans le but d\'améliorer l\'accompagnement et le déploiement du numérique avec une analyse et une présentation des résultats obtenus.', 'images_pfh\\Croix rouge française.png', 44, 'I14', 'croix-rouge'),
(21, 'Projet Cyber Sense', 'Sensibilisation à la sécurité sur internet.', 'Notre projet a pour buter de montre les potentiels attaques possibles qu’un lycéen, un étudiant ou un employé pourrait être victime. Notre but est donc de montrer les bonnes pratiques à adopter sur internet sous la forme d’un serious-game, de manière à rendre cela ludique et vivant.', 'images_pfh\\ESIEA.png', 102, 'E09', 'CyberSense'),
(22, 'Projet CyberGuardian', '“Record it, report it, don’t support it !”', 'Cyberguardian a pour objectif d’accompagner les victimes de cyberharcèlement et de sensibiliser le public face aux dangers qu’il peut rencontrer en ligne. \r\nNotre rôle au sein de ce projet consiste principalement à rédiger des articles sur différents sujets qui traitent de ces problèmes. Ces articles seront publiés sur la plateforme d’information de Cyberguardian.\r\n', 'images_pfh\\AffichePFH_CyberGuardian_720x420.PNG', 101, 'E09', 'Michael FRANÇOIS'),
(23, 'Apérobot', 'Conférence sur le sujet de la robotique autour d\'un apéritif', 'Le but de l\'Apérobot est de rassembler les amateurs et passionnés de robotique lors d\'une soirée de conférences et d\'activités sur ce thème. L\'objectif est de passer un moment convivial tout en se cultivant d\'avantage sur la robotique, ses avancées et ses nombreuses applications.', 'images_pfh\\affiche aperobot pfh.JPG', 26, 'I12a', 'aperobot'),
(24, 'Projet Mentaliste', 'Consiste à récupérer un maximum de vidéo d’entretien pour ensuite les faire analyser par un algorithme et mieux comprendre et améliorer la communication non verbale lors des entretiens de recrutement.', 'Il consiste à participer à une recherche avec le Laboratoire de Recherche en Intelligence Artificielle de l’ESIEA. Nous sommes en charge de collecter des vidéos d’entretiens pour ensuite les faire analyser par un algorithme pour mieux comprendre et améliorer le comportement humain lors d’entretiens de recrutement. ', 'images_pfh\\PFH_Mentaliste.JPG', 27, 'I12-a', 'mental'),
(25, 'Salon PFH – Scénarisation et design d’espace et logistique et installation technique', '', NULL, 'images_pfh\\ESIEA.png', 0, 'pas de room', 'Scenarisation'),
(26, 'Projet La Délégation PFH', 'Capacité d’adaptation, Rigueur, Travail d’équipe, Sens de l’écoute : autant de qualités que nous pourrons mettre au service de la société.» ', 'La délégation PFH, c’est un éventail de projets innovants, réalistes et axés sur la problématique du développement durable avec une finalité à but non lucratif et humain.\r\nNous avons pour but d’apporter à la plateforme PFH des projets provenant d’organisations externes à l’ESIEA tel que des associations, des entreprises à missions. C’est une nouvelle ouverture vers le monde extérieur, qui est en parfaite adéquation avec les dimensions relationnelle et humaine du cycle ingénieur.\r\n', 'images_pfh\\Affiche_delegation_PFH_numerique.png', 59, 'Extension - restauration', 'Delegation'),
(27, 'Projet Grand Reporteur', '', NULL, 'images_pfh\\ESIEA.png', 60, 'Extension canapés', 'Grand_Reporteur'),
(28, 'Projet Salon PFH – les Pilotes', '« Retrouvez-nous lors de l’ESIEA Inclusive Engineering Days pour découvrir les projets innovants des étudiants »', 'L’équipe des pilotes pour le salon des PFH a pour objectif d’organiser le salon avec 2 équipes (Communication et Logistique), afin de promouvoir les projets effectués par les étudiants tout au long de l’année et de leur permettre par ce salon de faire une présentation de leurs travaux effectués et d’être récompensé selon l’avis des jurys, des mentors et de la direction.', 'images_pfh\\ESIEA.png', 0, 'pas de room', 'Fleur Midon'),
(29, 'Projet Salon PFH – Communication interne et externe', '', NULL, 'images_pfh\\ESIEA.png', 0, 'pas de room', 'Comm_interne_externe'),
(30, 'Objectif Alternance', 'Toi aussi, viens profiter d’un accompagnement personnalisé pour trouver ton alternance !', 'Le Projet Objectif Alternance.\r\nUn projet PAR les Esiarques POUR les Esiarques intéressés par l’apprentissage.\r\nUn système de parrainage et d’ateliers pour atteindre le graal, un contrat de deux ou trois ans avec une entreprise qui vous correspond.\r\nCV, lettre de motivation, entretien, on vous assiste dans tous les domaines. Car, en temps de crise, l’entraide est primordiale pour la prospection !\r\n', 'images_pfh\\pfh_objectif_alternance_720_420.png', 29, 'I12a', 'obj altern'),
(31, 'Projet Les Hackeuses', 'Combattre l’inégalité sociale grâce à un numérique utile', 'Notre Projet a pour but de créer un scénario mettant en avant deux jeunes filles issues de milieux différents Ce scénario sera ensuite utilisé pour promouvoir l’école et susciter des vocations pour devenir des Ingénieures du numérique utile ESIEA.', 'images_pfh\\les Hackeuses.png', 54, 'Extension canapés', 'Hackeuses'),
(32, 'Projet Cérémonie de remise Diplôme ESIEA', 'Féliciter les diplômés d’aujourd’hui, c’est célébrer les ingénieurs du MONDE de demain.', 'Le projet de formation humaine « Cérémonie de remise de diplôme » consiste à organiser la cérémonie de remise de diplôme en fin d’année de l’ESIEA. Nous avons pour objectif d’organiser une journée mêlant souvenirs, satisfactions et festivités pour garder une image forte, au sein de l’école, des derniers moments des futures ingénieurs du Monde de demain.', 'images_pfh\\remise diplome.png', 35, 'I13', 'ceremonie'),
(33, 'Projet ESE', 'La conférence de cybersécurité made in ESIEA!', 'L’ESIEA Secure Edition plus communément appelé l’ESE est l’évènement dédié à la cybersécurité de l’ESIEA. Nous invitons des experts de différents domaines afin de vous proposer des conférences, atelier et workshop de qualité ! Au programme : un mix de sujet classique et d’actualité : ordinateur quantique, reverse engineering, OSINT, 5G et plus encore ..', 'images_pfh\\ESE.jpg', 104, 'E06', 'ESE'),
(35, 'Projet Inspeer', 'Vous en avez marre d’être seul, rejoignez l’expérience INSPEER et inspirez-vous !', 'INSPEER permet au travers d’expériences ludiques et intéressantes de participer à des sessions de collaboration qui permettent la mise en commun d’idée afin de développer des innovations collectives et de prendre conscience de l’état actuel de notre planète.\r\n\r\nDonc si vous avez envie de construire le monde de demain à base d’innovation sociale et écologique n’hésitez plus, passer à l’action et rejoignez INSPEER.\r\n', 'images_pfh\\ESIEA.png', 51, 'I16', 'Inspeer'),
(37, 'Projet Kart\'Esiea', 'Si tout parait contrôle, c’est\r\nque tu ne vas assez vite.', '? Depuis 3 ans, Kart’ESIEA favorise la découverte du sport\r\nmécanique aux étudiants, et l\'apprentissage de notions de bases en\r\npilotage et en technique.\r\nCréer des liens entre tous les étudiants, est dans notre ADN.\r\nNous organisons des courses inter-écoles et promos.\r\nNous avons plusieurs objectifs:\r\n• I. est l’organisation de courses de ?karting inter-école ainsi que\r\ndes cours de pilotage dans un complexe professionnel\r\npartenaire.\r\n• II. est la réalisation d’un Go-Kart électrique le plus\r\nperformant possible s\'adaptant aux normes actuelles.\r\n• III. consiste à gérer des réseaux sociaux de l’association pour\r\nla promouvoir le mieux possible et communiquer clairement sur\r\nnos projets.\r\n? Rejoins nous et repousse tes limites !!! ?', 'images_pfh\\ESIEA.png', 34, 'I13', 'Krt-Esiea'),
(39, 'Projet Sensibilisation à la cyber', 'Sensibilisation à la cybersécurité.', 'Nous avons 2 parties, une avec un atelier qui aborde différents thèmes pour sensibiliser à la cybersécurité, puis une partie phishing, ou comment préserver ses renseignements personnels.', 'images_pfh\\ESIEA.png', 106, 'E06', 'SensibilisationCyber'),
(40, 'Projets les Petits Soldats', 'Un enfant se bat, battez-vous avec lui.', 'Notre PFH s’intitule Les Petits Soldats, tout comme l’association qui nous a inspiré ce projet. Vous vous demandez surement pourquoi « Les Petits Soldats » pour un projet qui a pour but de réaliser des animations au sein d’hôpitaux et cliniques, simplement puisque nous considérons chacun de ces enfants hospitalisés comme des soldats, des soldats qui se battent tous les jours pour vaincre leur maladie.', 'images_pfh\\Visuel - PFH Les petits soldats.png', 61, 'Extension ', 'LesPetitsSoldats'),
(41, 'Projet RSE Esiea', 'Récupération Recyclage, Réutilisation de matériel informatique', 'Dans le cadre de ce projet, nous initions le projet 3R, un des éléments de l’économie circulaire en récupérant les divers équipements informatiques inutilisés, récupérer des composants encore utiles ou de les remettre à niveau pour les distribuer à des associations tierces pour leur réutilisation.', 'images_pfh\\RSE ESIEA.png', 53, 'I16', 'RSE'),
(43, 'Projet Monnaie Locale', 'Explorer des alternatives plus humaines', 'Une monnaie locale c\'est une monnaie complémentaire, notre but est d’étudier ces monnaies et surtout d\'étudier la possibilité d\'en créer une nous-même afin de paver la voie pour un éventuel projet l\'année prochaine.', 'images_pfh\\PFH affiche monnaie locale thumbnail.jpeg', 45, 'I14', 'Monnaie_Locale'),
(45, 'Projet Tech for Good Outfit', 'Exposition de vêtements qui respectent l’environnement, les animaux et l’homme.', 'Le projet consiste à mettre en avant des vêtements et des marques éco responsable et de montrer qu’il est possible de réduire l’impact écologique de l’industrie du textile, qui est la deuxième plus polluante au monde. Changeons nos habitudes !\r\nLe tout à travers une exposition sponsorisée par plusieurs marques, dont certaines très influentes.\r\n \r\n', 'images_pfh\\AFFICHE.jpg', 55, 'Extension face B02', 'TechGoodOutfit'),
(46, 'Projet Communication institutionnelle RSE', 'Récupération Recyclage, Réutilisation de matériel informatique', 'Dans le cadre de ce projet, nous initions le projet 3R, un des éléments de l’économie circulaire en récupérant les divers équipements informatiques inutilisés, récupérer des composants encore utiles ou de les remettre à niveau pour les distribuer à des associations tierces pour leur réutilisation.', 'images_pfh\\UNIVI.JPG', 52, 'I16', 'RSE'),
(47, 'Women In Africa', 'Women In Africa, let’s take our future in our hands !', '« La place de la femme c’est à la cuisine », qui de vous n’a pas entendu ou lu ce slogan partagé en boucle sur les réseaux sociaux ? Cela peut paraître dérisoire mais en réalité seule 1 entreprise sur 3 est détenue par une femme dans le monde. Des femmes entrepreneures et leaders africaines appuyés par des initiatives internationales tel que WIA ont mis en place avec l’ESIEA une campagne de communication et d’accompagnement dans leur projet pour attirer la diaspora francophone à travers un magazine juvénile et sensibiliser sur les mariages précoces.', 'images_pfh\\women in africa.jpg', 46, 'I14', 'woiaf'),
(48, 'Nuit du Jeu', 'Si tu veux passer une nuit mémorable, vient découvrir la Nuit du Jeu!', 'La NDJ - Nuit du Jeu, est un PFH consistant à faire profiter et découvrir aux étudiants, internes ou externes à l’école, de nombreux types de jeux pendant toute une nuit, de 19h le vendredi soir à 7h le lendemain matin. Nous mettons à disposition toutes sortes de jeux, que ce soit des jeux de sociétés, de cartes, des jeux vidéo, ou des jeux de rôles. Grâce au partenariat avec le Bureau des Jeux, nous pouvons en effet avoir accès à plusieurs consoles rétro, ordinateurs ainsi que des jeux de sociétés et des JDR.', 'images_pfh\\Affiche NDJ.JPG', 22, 'I11', 'NDJ'),
(49, 'Projet WebSérie', 'Ostium, la web-série de l’ESIEA', 'A l’ESIEA, de jeunes journalistes reçoivent un curieux colis. A l’intérieur, ils trouvent deux livres : un manuel d’informatique et un carnet. Néanmoins, le propriétaire de ces ouvrages semble n’avoir jamais existé. Comment nos jeunes journalistes vont-ils élucider cette affaire et en apprendre plus sur le passé mystérieux de l’école ? \r\nsure, nos étudiants ', 'images_pfh\\Affiche Théo HD 720x420 px.jpg', 63, 'Extension canapés', 'WebSerie'),
(50, 'Projet Solidaire Esiea', 'La solidarité est une force, unissons-nous !', 'Notre projet a pour but de construire un espace sur le campus d\'Ivry-sur-Seine afin de le transformer en un espace de stockage et d’échange de produits pour les élèves de l\'ESIEA. Cet espace permettra d\'organiser des distributions de produits de première nécessité provenant de supermarchés, d\'associations ou donnés par les élèves eux-mêmes afin d\'aider les élèves de l\'école en difficulté.', 'images_pfh\\Affiche Projet solidaire ESIEA 720x420.png', 62, 'Extension', 'Solidaire'),
(101, 'VIRIDIS', 'VIVONS BIEN, LIVRONS MIEUX', 'VIRIDIS est un service de livraison à domicile permettant de se faire livrer un peu de tout, que cela soit ses courses de proximité, alimentaires ou non, mais aussi ses colis. Avec une seule commande et donc un seul livreur, vous pouvez vous faire livrer différents articles provenant de différents commerces de votre ville. Un service soucieux des enjeux actuels tels que la situation des livreurs, l’aspect environnemental (en livrant à vélo), économique (mettre en avant les petits commerçants) et social (qui veut peut devenir livreur, renouer un lien de confiance, favoriser les personnes peu qualifiées professionnellement parlant).', 'images_pfh\\Affiche_VIRIDIS.png', 1, 'I02', 'Viridis'),
(102, 'ACADEMX', 'Pour une parité sans risque, dites oui à AcademX !', 'Nous, l’équipe AcademX voulons contribuer à une plus grande parité dans notre école. Nous avons décidé de communiquer auprès de jeunes collégiennes et lycéenne avec une bande dessinée décrivant la vie à l’école de Sasha et avec la création d’un jeu vidéo dans le même univers, où le joueur incarnera notre héroïne tout en apprenant l’informatique et la robotique.', 'images_pfh\\affiche3.jpg', 12, 'I03BIS', 'ACADEMX'),
(103, 'FIRE DAY', 'Fire Day will make your day !', 'Tout le monde a déjà connu le harcèlement ou a déjà été témoin que ce soit au travail, à l’école ou sur les réseaux sociaux. Personne ne peut y échapper, nous y sommes tous exposés dès notre plus jeune âge. C’est pour cela que le projet FIRE Day a été mis en place, pour sensibiliser sur ce problème et venir en aide au plus grand nombre !', 'images_pfh\\Pfh Fire Day -- A1.png', 2, 'I02', 'Fire_Day'),
(112, 'Escape Game Educatif', 'Sensibiliser les adolescents aux inégalités femme/homme grâce à un escape Game virtuel.', 'Sensibiliser les jeunes de façon ludique aux inégalités Femme/Homme avec la mise en œuvre d’un Escape Game vituel. Tout est pensé par l’équipe et mis en œuvre par l’équipe ; l’histoire, les énigmes, le design.', 'images_pfh\\Escape Game Educatif.png', 4, 'I02BIS', 'EscapeGameEducatif'),
(113, 'Equality for all', 'One for all !', 'Fondé par un groupe de 7 étudiants Esiearques fin 2020, le projet Equality for all compte désormais plus d’une vingtaine de membres volontaires et dévoués. Nous avons remarqué une différence notable de traitement entre sport féminin et sport masculin, qui ont des répercussions directes sur l’égalité H/F en général. Notre but est de résoudre ces injustices. Alors si tu es intéressé par notre projet n’hésite pas à nous rejoindre : ensemble nous sommes plus forts.', 'images_pfh\\Visuel PFH EqualityForAll.jpg', 13, 'I03BIS', 'EqualityForAll'),
(115, 'Aide Science College', '« Obtenez votre brevet en un clic ! »', 'Notre projet AideSciencesCollege vise à soutenir les collégiens en difficultés dans les matières scientifiques. Nous les aiderons dans leur apprentissage par le biais de vidéos de cours et d’exercices type brevet qui seront postés sur notre site web. Nous effectuerons également une distribution de fournitures pour les enfants pour promouvoir l’égalité des chances à l’école.', 'images_pfh\\AideScienceCollege.png', 5, 'I02BIS', 'AideScienceCollege'),
(118, 'Projet Education pour Tous', 'L’éducation est notre priorité !', 'Notre projet consiste en un site internet gratuit qui comportera cours, exercices, et tests attractifs tournés sur le thème du développement durable, ainsi que des professeurs qui seront joignables pour répondre aux questions.  \r\nLe but de notre projet est de donner une chance aux élèves en difficulté scolaire tout en leur faisant prendre conscience des problèmes environnementaux d\'aujourd\'hui.\r\n', 'images_pfh\\EducPourTous.png', 6, 'I02BIS', 'EducPourTous'),
(120, 'Manque de fournitures scolaires', 'Les fournitures, c\'est leur futur.', 'La finalité du projet consiste à récupérer des fournitures scolaires en bon état venant de personne qui n’en ont plus besoin. Nous souhaitons les redistribuer dans des établissements scolaires défavorisés à l’échelle internationale si notre projet prend de l’ampleur.', 'images_pfh\\affichePFH AEQUALIS - Manque de Fournitures Scolaires 720x420.png', 7, 'I02Bis', 'ManqueDeFourniteursScolaires'),
(122, 'Education & handicap', '', 'Le projet consiste à sensibiliser les enfants au quotidien des élèves français en situation de handicap à travers un livre éducatif, qui sera disponible dans leur école. Dans ce dernier, ils trouveront des informations sur le handicap des élèves et sur les difficultés rencontrées à l’école. De cette manière, les élèves pourront apporter leur aide aux AVS pendant les cours mais aussi en dehors.', 'images_pfh\\affiche_education_handicap.jpg', 8, 'I03', 'Education&Handicap'),
(128, 'ONELA Paris', 'Equality has no price', 'Notre projet ONÉLA Paris dénonce les inégalités de l’éducation dans le monde, en particulier dans les zones d’éducation prioritaires. Nous souhaitons venir en aide aux plus démunis en leur apportant un soutien matériel et scolaire. \r\nBénévolats et dons, quelqu’ils soient, sont les bienvenues. Pour plus d’informations, rendez-vous sur https://onelaparis.wixsite.com/website-1\r\nN’oubliez pas, Equality has no price.\r\n', 'images_pfh\\ONELA.png', 9, 'I03', 'ONELA'),
(130, 'ANTS EDUCATION', 'L’Éducation Pour Tous', 'Nous avons choisi de réaliser un site dont les bénéfices seront reversés à des Associations dans le domaine de l’éducation. Ce site sera une plateforme éducative où des élèves comme des professeurs pourront découvrir de nouveaux domaines. Nous voulons aider les élèves du monde entier au travers des Associations pour lesquelles les bénéfices seront reversés.', 'images_pfh\\ANTS 720-420.png', 10, 'I03', 'ANTS'),
(131, 'GLJS', 'Le GLJS est un projet de loi visant à réformer les méthodes de recrutement pour l\'obtention d\'un emploi.', 'Le GLJS est un projet de loi visant à diminuer le nombre d’inégalités dans le milieu du travail et notamment à réformer les méthodes de recrutement pour obtenir un emploi.\r\nNotre stratégie est de retirer toute information concernant le genre dans le processus.\r\n \r\n', 'images_pfh\\GLJS.png', 3, 'I02', 'GLJS'),
(135, 'Les Surdoués', 'Développement d’une application mobile d\'apprentissage à distance pour les collégiens et lycéens. Essayer des \"cours du soirs\" en groupe et à la maison.', 'Notre projet consiste à développer une application d\'apprentissage à distance, gratuite, pour les collégiens et les lycéens afin qu’ils puissent travailler les \"cours du soirs\", en individuel ou en groupe et à la maison.\r\nLe tout avec un interface simple et facile d\'utilisation, une base de cours disponibles ouvertement et une équipe de professeurs bénévoles et accessibles.\r\nDestiné à d\'élèves en difficulté mais motivés.\r\n', 'images_pfh\\Affiche 720x420px.png', 11, 'I03', 'Les_Surdoués');


--
-- Index pour les tables déchargées
--

--
-- Index pour la table `pst2a`
--
ALTER TABLE `pst2a`
  ADD PRIMARY KEY (`id_EquipePST`);

--
-- Index pour la table `pst3a`
--
ALTER TABLE `pst3a`
  ADD PRIMARY KEY (`id_EquipePST`);

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
